### ISSUE TITLE
Segmentation fault on aarch64/16k pages -- musl

### ISSUE THREAD

**Issue by 9ktz** [refi64/zypak#25]
Greetings. I'm running  alpinelinux on apple silicon as a daily driver and I've been facing the same error with numerous flatpaks which they all suffer from the same issue.

Running flatpak run com.zettlr.Zettlr for example yields
/app/bin/start-zettlr: line 2:     3 Segmentation fault      zypak-wrapper /app/zettlr/Zettlr "$@"

Running flatpak run md.obsidian.Obsidian yieds this
/app/bin/obsidian.sh: line 19:     3 Segmentation fault      zypak-wrapper /app/obsidian $@

5.19.0-0-asahi #1-Alpine SMP PREEMPT Tue, 09 Aug 2022 15:48:28 +0000 aarch64 GNU/Linux
Also keep in mind that the hardware has 16k pages as default and the asahi kernel follows suit. Fyi  the arm spec includes all 4,16,64k pagesizes as valid.

In case I can provide any additional usable info please let me know

**Comment by refi64** [comment]
This isn't related to Zypak, rather Chromium itself, and by extension Electron, segfaults on 16k page systems. This is [fixed in recent Chromium versions](https://chromium-review.googlesource.com/c/chromium/src/+/3542265), included in Electron 19 and 18.3.7+. Any apps just need to upgrade their Electron versions to work, unfortunately.

**Comment by 9ktz** [comment]
Glad to know, thanks
