### ISSUE TITLE
Add a USE_WAYLAND variable for forcing the Wayland backend

### ISSUE THREAD

**Issue by orowith2os** [refi64/zypak#28]
Currently, Electron is a bit weird with Wayland, and as such many apps hide support behind an environment variable.

I believe it would be useful to have a USE_WAYLAND var inside of zypak itself, so that packagers don't need to script the variable out themselves.

Additionally, maybe do a check for Wayland, and enable `WebRTCPipeWireCapturer` if true.

**Comment by refi64** [comment]
This would be something that goes in [cobalt](https://github.com/refi64/cobalt), which doesn't work on Electron yet because...I haven't gotten around to it. :sweat_smile:

That being said, I'm not sure if we need much to change for this specifically: cobalt already reads browser-specific flags from a `.conf` file where you could set `--ozone-platform=wayland`. So the main issue remaining would just be making it Electron-friendly.

**Comment by orowith2os** [comment]
*nit, close as not planned, not completed*
