### ISSUE TITLE
repl doesn't work in Icalingua++

### ISSUE THREAD

**Issue by leohearts** [refi64/zypak#29]
stdin is redirected
https://github.com/refi64/zypak/blob/64f6ccfdfd223cc2d2d68608ef42b8ff2fd6400e/zypak-wrapper.sh#L13

**Comment by refi64** [comment]
This is mostly intentional so that the sandboxed processes [can't seek in stdio descriptors](https://bugs.chromium.org/p/chromium/issues/detail?id=376567) (though perhaps this is less of an issue entirely on Linux?).

I have to ask though: why on earth does a graphical Electron app also have a REPL :sweat_smile:

**Comment by leohearts** [comment]
> 

idk im just maintaining this flatpak package .
It's for sending commands to the main process as this is a chatbot frontend.

**Comment by leohearts** [comment]
Anyway we got a patch so it works (?

**Comment by refi64** [comment]
@leohearts please try the latest zypak main branch (instructions to do so are in the README) and lmk if it works now.
